name: HerokuDeploy
 
on:
  push:
    branches:
      - master
 
jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
    - name: Prettier Action
      uses: creyD/prettier_action@v3.3
      with:
        same_commit: True
        only_changed: True
    - uses: actions/checkout@v1
    - name: Build and deploy the Docker image for server
      env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          APP_NAME: ${{ 'webrtc-video-conferencing' }}
      run: |
        docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com
        heroku container:push web -a $APP_NAME
        heroku container:release web -a $APP_NAME
